/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home.dashboard.com;

import form.login.com.login_admin;
import java.awt.Button;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.UIManager;
import java.io.File;
import javax.swing.*;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import pembayaranspp.KoneksiDB;
import pembayaranspp.UserSession;

/**
 *
 * @author JUNIARGO
 */
public class Dashboard extends javax.swing.JFrame {
    Connection con = KoneksiDB.getConnection();
    ResultSet rs;
    DefaultTableModel model;
    CRUD_Spp crud_spp = new CRUD_Spp();
    CRUD_Siswa crud_siswa = new CRUD_Siswa();
    CRUD_Kelas crud_kelas = new CRUD_Kelas();
    CRUD_Petugas crud_petugas = new CRUD_Petugas();
    FormTransaksi form_transaksi = new FormTransaksi();


    //get user data session
    String id = UserSession.get_id();
    String username = UserSession.get_username();
    String nama = UserSession.get_nama();
    String level = UserSession.get_level();
    String nisn = UserSession.get_nisn();
    String nama_siswa = UserSession.get_nama_siswa();
    /**
     * Creates new form dashboard_admin
     */
    
    public Dashboard() {
        initComponents();
        pnltabed.setEnabledAt(1, false);
    }
    
    public void dashAdmin() { 
        tabelSpp();    
        tabelTrans();
//        jumlahDataMaster();
//        t_Level.setText("ADMINISTRATOR");
        tNama_user.setText(nama);
        lbl_user.setText("Selamat Datang "+nama);
    }
    
     public void dashPetugas() {    
        tabelSpp();    
        tabelTrans();
//        jumlahDataMaster();
//        t_Level.setText("PETUGAS");
        tNama_user.setText(nama);   
        lbl_user.setText(nama);
        //block akses
//        mnDataMaster.setVisible(false);
//        mnLaporan.setVisible(false);
        btn_kelas.setVisible(false);
        btn_kelas.setVisible(false);
        btn_siswa.setVisible(false);
        btn_spp.setVisible(false);
        btn_petugas.setVisible(false);
        btn_administrator.setText("Home");
        btn_laporan.setVisible(false);
        pnltabed.setTitleAt(0,"Petugas");

    }
     public void dashSiswa() {    
        tabelSpp();    
        tabelSiswa();
//        jumlahDataMaster();
//        t_Level.setText("PETUGAS");
        tNama_user.setText(nama_siswa); 
        lbl_user.setText(nama_siswa);
        //block akses
        btn_kelas.setVisible(false);
        btn_kelas.setVisible(false);
        btn_siswa.setVisible(false);
        btn_spp.setVisible(false);
        btn_petugas.setVisible(false);
        btn_administrator.setVisible(false);
        btn_laporan.setVisible(false);
        btn_pembayaran.setVisible(false);
        jLabelCari.setVisible(false);
        cariTransaksi.setVisible(false);
        pnltabed.setTitleAt(0,"History");
    }
//    Navigasi Button Color
    Color backNavHover = new Color(255,255,255);
    Color foreNavHover = new Color(0,0,0);
    Color backNavNormal = new Color(255,153,255);
    Color foreNavNormal = new Color(255,255,255);

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jml_petugas = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jml_siswa = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jml_kelas = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lbl_fotouser = new javax.swing.JLabel();
        tNama_user = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_administrator = new javax.swing.JButton();
        btn_spp = new javax.swing.JButton();
        btn_kelas = new javax.swing.JButton();
        btn_siswa = new javax.swing.JButton();
        btn_petugas = new javax.swing.JButton();
        btn_pembayaran = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        pnltabed = new javax.swing.JTabbedPane();
        pnlAdmin = new javax.swing.JPanel();
        jLabelCari = new javax.swing.JLabel();
        cariTransaksi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtabelSpp = new javax.swing.JTable();
        mainPnl = new javax.swing.JPanel();

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PETUGAS ");

        jml_petugas.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jml_petugas.setForeground(new java.awt.Color(255, 255, 255));
        jml_petugas.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jml_petugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jml_petugas)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SISWA");

        jml_siswa.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jml_siswa.setForeground(new java.awt.Color(255, 255, 255));
        jml_siswa.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jml_siswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jml_siswa)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("KELAS");

        jml_kelas.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jml_kelas.setForeground(new java.awt.Color(255, 255, 255));
        jml_kelas.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jml_kelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jml_kelas)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);

        pnlMenu.setBackground(new java.awt.Color(255, 153, 255));
        pnlMenu.setPreferredSize(new java.awt.Dimension(180, 531));
        pnlMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        lbl_fotouser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fotouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Circled User Male Skin Type 7.png"))); // NOI18N
        lbl_fotouser.setPreferredSize(new java.awt.Dimension(150, 100));
        pnlMenu.add(lbl_fotouser);

        tNama_user.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        tNama_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tNama_user.setText("Admin");
        tNama_user.setPreferredSize(new java.awt.Dimension(150, 25));
        pnlMenu.add(tNama_user);

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlMenu.add(jPanel3);

        btn_administrator.setBackground(new java.awt.Color(255, 153, 255));
        btn_administrator.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_administrator.setForeground(new java.awt.Color(255, 255, 255));
        btn_administrator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Adminitrator.png"))); // NOI18N
        btn_administrator.setText("Administrator");
        btn_administrator.setActionCommand("");
        btn_administrator.setAlignmentY(0.0F);
        btn_administrator.setBorder(null);
        btn_administrator.setBorderPainted(false);
        btn_administrator.setContentAreaFilled(false);
        btn_administrator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_administrator.setDefaultCapable(false);
        btn_administrator.setFocusable(false);
        btn_administrator.setHideActionText(true);
        btn_administrator.setOpaque(true);
        btn_administrator.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_administrator.setRequestFocusEnabled(false);
        btn_administrator.setRolloverEnabled(false);
        btn_administrator.setVerifyInputWhenFocusTarget(false);
        btn_administrator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_administratorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_administratorMouseExited(evt);
            }
        });
        btn_administrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administratorActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_administrator);

        btn_spp.setBackground(new java.awt.Color(255, 153, 255));
        btn_spp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_spp.setForeground(new java.awt.Color(255, 255, 255));
        btn_spp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payment.png"))); // NOI18N
        btn_spp.setText("SPP");
        btn_spp.setActionCommand("");
        btn_spp.setAlignmentY(0.0F);
        btn_spp.setBorder(null);
        btn_spp.setBorderPainted(false);
        btn_spp.setContentAreaFilled(false);
        btn_spp.setDefaultCapable(false);
        btn_spp.setFocusCycleRoot(true);
        btn_spp.setFocusable(false);
        btn_spp.setHideActionText(true);
        btn_spp.setInheritsPopupMenu(true);
        btn_spp.setOpaque(true);
        btn_spp.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_spp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payment.png"))); // NOI18N
        btn_spp.setRequestFocusEnabled(false);
        btn_spp.setRolloverEnabled(false);
        btn_spp.setVerifyInputWhenFocusTarget(false);
        btn_spp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sppMouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sppMouseExited1(evt);
            }
        });
        btn_spp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sppActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_spp);

        btn_kelas.setBackground(new java.awt.Color(255, 153, 255));
        btn_kelas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_kelas.setForeground(new java.awt.Color(255, 255, 255));
        btn_kelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Class.png"))); // NOI18N
        btn_kelas.setText("Kelas");
        btn_kelas.setActionCommand("");
        btn_kelas.setAlignmentY(0.0F);
        btn_kelas.setBorder(null);
        btn_kelas.setBorderPainted(false);
        btn_kelas.setContentAreaFilled(false);
        btn_kelas.setDefaultCapable(false);
        btn_kelas.setFocusCycleRoot(true);
        btn_kelas.setFocusable(false);
        btn_kelas.setHideActionText(true);
        btn_kelas.setInheritsPopupMenu(true);
        btn_kelas.setOpaque(true);
        btn_kelas.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_kelas.setRequestFocusEnabled(false);
        btn_kelas.setRolloverEnabled(false);
        btn_kelas.setVerifyInputWhenFocusTarget(false);
        btn_kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_kelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_kelasMouseExited(evt);
            }
        });
        btn_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kelasActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_kelas);

        btn_siswa.setBackground(new java.awt.Color(255, 153, 255));
        btn_siswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_siswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Student.png"))); // NOI18N
        btn_siswa.setText("Siswa");
        btn_siswa.setActionCommand("");
        btn_siswa.setAlignmentY(0.0F);
        btn_siswa.setBorder(null);
        btn_siswa.setBorderPainted(false);
        btn_siswa.setContentAreaFilled(false);
        btn_siswa.setDefaultCapable(false);
        btn_siswa.setFocusCycleRoot(true);
        btn_siswa.setFocusable(false);
        btn_siswa.setHideActionText(true);
        btn_siswa.setInheritsPopupMenu(true);
        btn_siswa.setOpaque(true);
        btn_siswa.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_siswa.setRequestFocusEnabled(false);
        btn_siswa.setRolloverEnabled(false);
        btn_siswa.setVerifyInputWhenFocusTarget(false);
        btn_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_siswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_siswaMouseExited(evt);
            }
        });
        btn_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siswaActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_siswa);

        btn_petugas.setBackground(new java.awt.Color(255, 153, 255));
        btn_petugas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_petugas.setForeground(new java.awt.Color(255, 255, 255));
        btn_petugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Officer.png"))); // NOI18N
        btn_petugas.setText("Petugas");
        btn_petugas.setActionCommand("");
        btn_petugas.setAlignmentY(0.0F);
        btn_petugas.setBorder(null);
        btn_petugas.setBorderPainted(false);
        btn_petugas.setContentAreaFilled(false);
        btn_petugas.setDefaultCapable(false);
        btn_petugas.setFocusCycleRoot(true);
        btn_petugas.setFocusable(false);
        btn_petugas.setHideActionText(true);
        btn_petugas.setInheritsPopupMenu(true);
        btn_petugas.setOpaque(true);
        btn_petugas.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_petugas.setRequestFocusEnabled(false);
        btn_petugas.setRolloverEnabled(false);
        btn_petugas.setVerifyInputWhenFocusTarget(false);
        btn_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_petugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_petugasMouseExited(evt);
            }
        });
        btn_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_petugasActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_petugas);

        btn_pembayaran.setBackground(new java.awt.Color(255, 153, 255));
        btn_pembayaran.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pembayaran.setForeground(new java.awt.Color(255, 255, 255));
        btn_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Card.png"))); // NOI18N
        btn_pembayaran.setText("Pembayaran");
        btn_pembayaran.setActionCommand("");
        btn_pembayaran.setAlignmentY(0.0F);
        btn_pembayaran.setBorder(null);
        btn_pembayaran.setBorderPainted(false);
        btn_pembayaran.setContentAreaFilled(false);
        btn_pembayaran.setDefaultCapable(false);
        btn_pembayaran.setFocusCycleRoot(true);
        btn_pembayaran.setFocusable(false);
        btn_pembayaran.setHideActionText(true);
        btn_pembayaran.setInheritsPopupMenu(true);
        btn_pembayaran.setOpaque(true);
        btn_pembayaran.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_pembayaran.setRequestFocusEnabled(false);
        btn_pembayaran.setRolloverEnabled(false);
        btn_pembayaran.setVerifyInputWhenFocusTarget(false);
        btn_pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pembayaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pembayaranMouseExited(evt);
            }
        });
        btn_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembayaranActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_pembayaran);

        btn_laporan.setBackground(new java.awt.Color(255, 153, 255));
        btn_laporan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Graph Report.png"))); // NOI18N
        btn_laporan.setText("Laporan");
        btn_laporan.setActionCommand("");
        btn_laporan.setAlignmentY(0.0F);
        btn_laporan.setBorder(null);
        btn_laporan.setBorderPainted(false);
        btn_laporan.setContentAreaFilled(false);
        btn_laporan.setDefaultCapable(false);
        btn_laporan.setFocusCycleRoot(true);
        btn_laporan.setFocusable(false);
        btn_laporan.setHideActionText(true);
        btn_laporan.setInheritsPopupMenu(true);
        btn_laporan.setOpaque(true);
        btn_laporan.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_laporan.setRequestFocusEnabled(false);
        btn_laporan.setRolloverEnabled(false);
        btn_laporan.setVerifyInputWhenFocusTarget(false);
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_laporanMouseExited(evt);
            }
        });
        pnlMenu.add(btn_laporan);

        btn_logout.setBackground(new java.awt.Color(255, 153, 255));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setActionCommand("");
        btn_logout.setAlignmentY(0.0F);
        btn_logout.setBorder(null);
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setDefaultCapable(false);
        btn_logout.setFocusCycleRoot(true);
        btn_logout.setFocusable(false);
        btn_logout.setHideActionText(true);
        btn_logout.setInheritsPopupMenu(true);
        btn_logout.setOpaque(true);
        btn_logout.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_logout.setRequestFocusEnabled(false);
        btn_logout.setRolloverEnabled(false);
        btn_logout.setVerifyInputWhenFocusTarget(false);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_logout);

        getContentPane().add(pnlMenu, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(242, 185, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(833, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lbl_user.setBackground(new java.awt.Color(242, 209, 227));
        lbl_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AdminitratorBlck.png"))); // NOI18N
        lbl_user.setText("Selamat Datang di Administrator");
        jPanel1.add(lbl_user, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnltabed.setBackground(new java.awt.Color(255, 255, 255));

        pnlAdmin.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCari.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCari.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCari.setText("Cari Transaksi");
        pnlAdmin.add(jLabelCari);

        cariTransaksi.setPreferredSize(new java.awt.Dimension(900, 25));
        cariTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariTransaksiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cariTransaksiKeyTyped(evt);
            }
        });
        pnlAdmin.add(cariTransaksi);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1150, 300));

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransaksi.setEnabled(false);
        jScrollPane1.setViewportView(tableTransaksi);

        pnlAdmin.add(jScrollPane1);

        jPanel4.setPreferredSize(new java.awt.Dimension(1150, 452));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA ANGKATAN");
        jLabel2.setPreferredSize(new java.awt.Dimension(1000, 20));

        JtabelSpp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        JtabelSpp.setColumnSelectionAllowed(true);
        JtabelSpp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JtabelSpp.setEnabled(false);
        jScrollPane2.setViewportView(JtabelSpp);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(339, 339, 339))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlAdmin.add(jPanel4);

        pnltabed.addTab("Administrator", pnlAdmin);

        mainPnl.setBackground(new java.awt.Color(255, 255, 255));
        mainPnl.setLayout(new java.awt.BorderLayout());
        pnltabed.addTab("Intruksi", mainPnl);

        jPanel2.add(pnltabed, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1093, 851));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_administratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_administratorMouseEntered
        // TODO add your handling code here:
        btn_administrator.setBackground(backNavHover);
        btn_administrator.setForeground(foreNavHover);
        btn_administrator.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\AdminitratorBlck.png"));
    }//GEN-LAST:event_btn_administratorMouseEntered

    private void btn_administratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_administratorMouseExited
        // TODO add your handling code here:
        btn_administrator.setBackground(backNavNormal);
        btn_administrator.setForeground(foreNavNormal);
        btn_administrator.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Adminitrator.png"));
    }//GEN-LAST:event_btn_administratorMouseExited

    private void btn_sppMouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sppMouseEntered1
        // TODO add your handling code here:
        btn_spp.setBackground(backNavHover);
        btn_spp.setForeground(foreNavHover);
        btn_spp.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\paymentblck.png"));

    }//GEN-LAST:event_btn_sppMouseEntered1

    private void btn_sppMouseExited1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sppMouseExited1
        // TODO add your handling code here:
        btn_spp.setBackground(backNavNormal);
        btn_spp.setForeground(foreNavNormal);
        btn_spp.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\payment.png"));

    }//GEN-LAST:event_btn_sppMouseExited1

    private void btn_kelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelasMouseEntered
        // TODO add your handling code here:
        btn_kelas.setBackground(backNavHover);
        btn_kelas.setForeground(foreNavHover);
        btn_kelas.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Classblck.png"));

    }//GEN-LAST:event_btn_kelasMouseEntered

    private void btn_kelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelasMouseExited
        // TODO add your handling code here:
        btn_kelas.setBackground(backNavNormal);
        btn_kelas.setForeground(foreNavNormal);
        btn_kelas.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Class.png"));
    }//GEN-LAST:event_btn_kelasMouseExited

    private void btn_siswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siswaMouseEntered
        // TODO add your handling code here:
        btn_siswa.setBackground(backNavHover);
        btn_siswa.setForeground(foreNavHover);
        btn_siswa.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Studentblck.png"));

    }//GEN-LAST:event_btn_siswaMouseEntered

    private void btn_siswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siswaMouseExited
        // TODO add your handling code here:
        btn_siswa.setBackground(backNavNormal);
        btn_siswa.setForeground(foreNavNormal);
        btn_siswa.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Student.png"));

    }//GEN-LAST:event_btn_siswaMouseExited

    private void btn_petugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseEntered
        // TODO add your handling code here:
        btn_petugas.setBackground(backNavHover);
        btn_petugas.setForeground(foreNavHover);
        btn_petugas.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Officerblck.png"));
    }//GEN-LAST:event_btn_petugasMouseEntered

    private void btn_petugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseExited
        // TODO add your handling code here:
        btn_petugas.setBackground(backNavNormal);
        btn_petugas.setForeground(foreNavNormal);
        btn_petugas.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Officer.png"));
    }//GEN-LAST:event_btn_petugasMouseExited

    private void btn_pembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembayaranMouseEntered
        // TODO add your handling code here:
        btn_pembayaran.setBackground(backNavHover);
        btn_pembayaran.setForeground(foreNavHover);
        btn_pembayaran.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Cardblck.png"));
    }//GEN-LAST:event_btn_pembayaranMouseEntered

    private void btn_pembayaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembayaranMouseExited
        // TODO add your handling code here:
        btn_pembayaran.setBackground(backNavNormal);
        btn_pembayaran.setForeground(foreNavNormal);
        btn_pembayaran.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Card.png"));
    }//GEN-LAST:event_btn_pembayaranMouseExited

    private void btn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseEntered
        // TODO add your handling code here:
        btn_laporan.setBackground(backNavHover);
        btn_laporan.setForeground(foreNavHover);
        btn_laporan.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Graphblck.png"));
    }//GEN-LAST:event_btn_laporanMouseEntered

    private void btn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseExited
        // TODO add your handling code here:
        btn_laporan.setBackground(backNavNormal);
        btn_laporan.setForeground(foreNavNormal);
        btn_laporan.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Graph Report.png"));
    }//GEN-LAST:event_btn_laporanMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
        btn_logout.setBackground(backNavHover);
        btn_logout.setForeground(foreNavHover);
        btn_logout.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Logoutblk.png"));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
        btn_logout.setBackground(backNavNormal);
        btn_logout.setForeground(foreNavNormal);
        btn_logout.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Logout.png"));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new login_admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_administratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administratorActionPerformed
        // TODO add your handling code here:
        pnltabed.setEnabledAt(0,true);        
        pnltabed.setEnabledAt(1,false);
        pnltabed.setSelectedIndex(0);
    }//GEN-LAST:event_btn_administratorActionPerformed

    private void btn_sppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sppActionPerformed
        // TODO add your handling code here:
        pnltabed.setEnabledAt(0,false);        
        pnltabed.setEnabledAt(1,true);
        pnltabed.setSelectedIndex(1);
        mainPnl.add(crud_siswa).setVisible(false);
        mainPnl.add(crud_kelas).setVisible(false);
        mainPnl.add(crud_petugas).setVisible(false);
        mainPnl.add(form_transaksi).setVisible(false);
        mainPnl.add(crud_spp).setVisible(true);
    }//GEN-LAST:event_btn_sppActionPerformed

    private void cariTransaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTransaksiKeyReleased
        tabelTrans();
    }//GEN-LAST:event_cariTransaksiKeyReleased

    private void cariTransaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTransaksiKeyTyped
        tabelTrans();
    }//GEN-LAST:event_cariTransaksiKeyTyped

    private void btn_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siswaActionPerformed
        // TODO add your handling code here:
        pnltabed.setEnabledAt(0,false);        
        pnltabed.setEnabledAt(1,true);
        pnltabed.setSelectedIndex(1);
        mainPnl.add(crud_kelas).setVisible(false);
        mainPnl.add(crud_spp).setVisible(false);
        mainPnl.add(crud_petugas).setVisible(false);
        mainPnl.add(form_transaksi).setVisible(false);
        mainPnl.add(crud_siswa).setVisible(true);

    }//GEN-LAST:event_btn_siswaActionPerformed

    private void btn_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kelasActionPerformed
        // TODO add your handling code here:
        pnltabed.setEnabledAt(0,false);        
        pnltabed.setEnabledAt(1,true);
        pnltabed.setSelectedIndex(1);
        mainPnl.add(crud_siswa).setVisible(false);
        mainPnl.add(crud_spp).setVisible(false);
        mainPnl.add(crud_petugas).setVisible(false);
        mainPnl.add(form_transaksi).setVisible(false);
        mainPnl.add(crud_kelas).setVisible(true);
    }//GEN-LAST:event_btn_kelasActionPerformed

    private void btn_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_petugasActionPerformed
        // TODO add your handling code here:
        pnltabed.setEnabledAt(0,false);        
        pnltabed.setEnabledAt(1,true);
        pnltabed.setSelectedIndex(1);
        mainPnl.add(crud_siswa).setVisible(false);
        mainPnl.add(crud_kelas).setVisible(false);
        mainPnl.add(crud_spp).setVisible(false);
        mainPnl.add(form_transaksi).setVisible(false);
        mainPnl.add(crud_petugas).setVisible(true);

    }//GEN-LAST:event_btn_petugasActionPerformed

    private void btn_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembayaranActionPerformed
        // TODO add your handling code here:
//        new FormTransaksiT().setVisible(true); 
//        dispose();
        pnltabed.setEnabledAt(0,false);        
        pnltabed.setEnabledAt(1,true);
        pnltabed.setSelectedIndex(1);
        
        FormTransaksi formTransaksi = new FormTransaksi();
        formTransaksi.resetForm();
        formTransaksi.repaint();
        
        mainPnl.add(crud_siswa).setVisible(false);
        mainPnl.add(crud_kelas).setVisible(false);
        mainPnl.add(crud_spp).setVisible(false);
        mainPnl.add(crud_petugas).setVisible(false);
        mainPnl.add(form_transaksi).setVisible(true);
    }//GEN-LAST:event_btn_pembayaranActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    public void tabelTrans() {
        String[] judul = {"Tanggal","No. Transaksi","NISN","Nama Siswa","Bulan Dibayar","Tahun","Jumlah Bayar","Petugas"};
        model = new DefaultTableModel(judul,0);
        tableTransaksi.setModel(model);
        String sql = "SELECT *,petugas.*, siswa.* from pembayaran INNER JOIN petugas USING(id_petugas) INNER JOIN siswa USING(nisn) where id_pembayaran like '%"+cariTransaksi.getText()+"%' or nisn like '%"+cariTransaksi.getText()+"%'or nama like '%"+cariTransaksi.getText()+"%' or tahun_dibayar like '%"+cariTransaksi.getText()+"%'";
        try {
            rs = con.createStatement().executeQuery(sql);
           
            while(rs.next()) {
               String tanggal = rs.getString("tgl_bayar");
               String no_transaksi = rs.getString("id_pembayaran");
               String nisn = rs.getString("nisn");              
               String nama = rs.getString("nama");              
               String bulan = rs.getString("bulan_dibayar");               
               String tahun = rs.getString("tahun_dibayar");
               String jumlah = rs.getString("jumlah_bayar");
               String petugas = rs.getString("nama_petugas");
               
               String[] data = {tanggal,no_transaksi,nisn,nama,bulan,tahun, jumlah,petugas};
               model.addRow(data);
           }
        }catch(Exception e) {
           System.out.println(e);
        }    
    }
    
    public void tabelSiswa() {
        String[] judul = {"Tanggal","No. Transaksi","NISN","Nama Siswa","Bulan Dibayar","Tahun","Jumlah Bayar","Petugas"};
        model = new DefaultTableModel(judul,0);
        tableTransaksi.setModel(model);
        String sql = "SELECT *,petugas.*, siswa.* from pembayaran INNER JOIN petugas USING(id_petugas) INNER JOIN siswa USING(nisn) where nama like '%"+nama_siswa+"%' ";
        try {
            rs = con.createStatement().executeQuery(sql);
           
            while(rs.next()) {
               String tanggal = rs.getString("tgl_bayar");
               String no_transaksi = rs.getString("id_pembayaran");
               String nisn = rs.getString("nisn");              
               String nama = rs.getString("nama");              
               String bulan = rs.getString("bulan_dibayar");               
               String tahun = rs.getString("tahun_dibayar");
               String jumlah = rs.getString("jumlah_bayar");
               String petugas = rs.getString("nama_petugas");
               
               String[] data = {tanggal,no_transaksi,nisn,nama,bulan,tahun, jumlah,petugas};
               model.addRow(data);
           }
        }catch(Exception e) {
           System.out.println(e);
        }    
    }
    
    private void tabelSpp() {
        String[] judul = {"Tahun","Nominal"};
        model = new DefaultTableModel(judul,0);
        JtabelSpp.setModel(model);
        String sql = "SELECT tahun, nominal from spp";
       
        try {
            rs = con.createStatement().executeQuery(sql);
            
            while(rs.next()) {
               String tahun = rs.getString("tahun");
               String nominal = rs.getString("nominal");
                
               String[] data = {tahun,nominal};
               model.addRow(data);
           }
        }catch(Exception e) {
           System.out.println(e);
        }
    }       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtabelSpp;
    private javax.swing.JButton btn_administrator;
    private javax.swing.JButton btn_kelas;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pembayaran;
    private javax.swing.JButton btn_petugas;
    private javax.swing.JButton btn_siswa;
    private javax.swing.JButton btn_spp;
    private javax.swing.JTextField cariTransaksi;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCari;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jml_kelas;
    private javax.swing.JLabel jml_petugas;
    private javax.swing.JLabel jml_siswa;
    private javax.swing.JLabel lbl_fotouser;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JTabbedPane pnltabed;
    private javax.swing.JLabel tNama_user;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
