/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home.dashboard.com;

import form.login.com.login_admin;
import java.awt.Button;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.UIManager;

/**
 *
 * @author JUNIARGO
 */
public class dashboard_admin extends javax.swing.JFrame {

    /**
     * Creates new form dashboard_admin
     */
    public dashboard_admin() {
        initComponents();
    }
    
//    Navigasi Button Color
    Color backNavHover = new Color(255,255,255);
    Color foreNavHover = new Color(0,0,0);
    Color backNavNormal = new Color(255,153,255);
    Color foreNavNormal = new Color(255,255,255);

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lbl_fotouser = new javax.swing.JLabel();
        lbl_namauser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_administrator = new javax.swing.JButton();
        btn_spp = new javax.swing.JButton();
        btn_kelas = new javax.swing.JButton();
        btn_siswa = new javax.swing.JButton();
        btn_petugas = new javax.swing.JButton();
        btn_pembayaran = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        pnlMenu.setBackground(new java.awt.Color(255, 153, 255));
        pnlMenu.setPreferredSize(new java.awt.Dimension(180, 531));
        pnlMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        lbl_fotouser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fotouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Circled User Male Skin Type 7.png"))); // NOI18N
        lbl_fotouser.setPreferredSize(new java.awt.Dimension(150, 100));
        pnlMenu.add(lbl_fotouser);

        lbl_namauser.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lbl_namauser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_namauser.setText("Admin");
        lbl_namauser.setPreferredSize(new java.awt.Dimension(150, 25));
        pnlMenu.add(lbl_namauser);

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlMenu.add(jPanel3);

        btn_administrator.setBackground(new java.awt.Color(255, 153, 255));
        btn_administrator.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_administrator.setForeground(new java.awt.Color(255, 255, 255));
        btn_administrator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Adminitrator.png"))); // NOI18N
        btn_administrator.setText("Administrator");
        btn_administrator.setActionCommand("");
        btn_administrator.setAlignmentY(0.0F);
        btn_administrator.setBorder(null);
        btn_administrator.setBorderPainted(false);
        btn_administrator.setContentAreaFilled(false);
        btn_administrator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_administrator.setDefaultCapable(false);
        btn_administrator.setFocusCycleRoot(true);
        btn_administrator.setFocusTraversalPolicyProvider(true);
        btn_administrator.setHideActionText(true);
        btn_administrator.setInheritsPopupMenu(true);
        btn_administrator.setOpaque(true);
        btn_administrator.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_administrator.setRequestFocusEnabled(false);
        btn_administrator.setRolloverEnabled(false);
        btn_administrator.setVerifyInputWhenFocusTarget(false);
        btn_administrator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_administratorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_administratorMouseExited(evt);
            }
        });
        pnlMenu.add(btn_administrator);

        btn_spp.setBackground(new java.awt.Color(255, 153, 255));
        btn_spp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_spp.setForeground(new java.awt.Color(255, 255, 255));
        btn_spp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payment.png"))); // NOI18N
        btn_spp.setText("SPP");
        btn_spp.setActionCommand("");
        btn_spp.setAlignmentY(0.0F);
        btn_spp.setBorder(null);
        btn_spp.setBorderPainted(false);
        btn_spp.setContentAreaFilled(false);
        btn_spp.setDefaultCapable(false);
        btn_spp.setFocusCycleRoot(true);
        btn_spp.setFocusTraversalPolicyProvider(true);
        btn_spp.setHideActionText(true);
        btn_spp.setInheritsPopupMenu(true);
        btn_spp.setOpaque(true);
        btn_spp.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_spp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payment.png"))); // NOI18N
        btn_spp.setRequestFocusEnabled(false);
        btn_spp.setRolloverEnabled(false);
        btn_spp.setVerifyInputWhenFocusTarget(false);
        btn_spp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sppMouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sppMouseExited1(evt);
            }
        });
        pnlMenu.add(btn_spp);

        btn_kelas.setBackground(new java.awt.Color(255, 153, 255));
        btn_kelas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_kelas.setForeground(new java.awt.Color(255, 255, 255));
        btn_kelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Class.png"))); // NOI18N
        btn_kelas.setText("Kelas");
        btn_kelas.setActionCommand("");
        btn_kelas.setAlignmentY(0.0F);
        btn_kelas.setBorder(null);
        btn_kelas.setBorderPainted(false);
        btn_kelas.setContentAreaFilled(false);
        btn_kelas.setDefaultCapable(false);
        btn_kelas.setFocusCycleRoot(true);
        btn_kelas.setFocusTraversalPolicyProvider(true);
        btn_kelas.setHideActionText(true);
        btn_kelas.setInheritsPopupMenu(true);
        btn_kelas.setOpaque(true);
        btn_kelas.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_kelas.setRequestFocusEnabled(false);
        btn_kelas.setRolloverEnabled(false);
        btn_kelas.setVerifyInputWhenFocusTarget(false);
        btn_kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_kelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_kelasMouseExited(evt);
            }
        });
        pnlMenu.add(btn_kelas);

        btn_siswa.setBackground(new java.awt.Color(255, 153, 255));
        btn_siswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_siswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Student.png"))); // NOI18N
        btn_siswa.setText("Siswa");
        btn_siswa.setActionCommand("");
        btn_siswa.setAlignmentY(0.0F);
        btn_siswa.setBorder(null);
        btn_siswa.setBorderPainted(false);
        btn_siswa.setContentAreaFilled(false);
        btn_siswa.setDefaultCapable(false);
        btn_siswa.setFocusCycleRoot(true);
        btn_siswa.setFocusTraversalPolicyProvider(true);
        btn_siswa.setHideActionText(true);
        btn_siswa.setInheritsPopupMenu(true);
        btn_siswa.setOpaque(true);
        btn_siswa.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_siswa.setRequestFocusEnabled(false);
        btn_siswa.setRolloverEnabled(false);
        btn_siswa.setVerifyInputWhenFocusTarget(false);
        btn_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_siswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_siswaMouseExited(evt);
            }
        });
        pnlMenu.add(btn_siswa);

        btn_petugas.setBackground(new java.awt.Color(255, 153, 255));
        btn_petugas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_petugas.setForeground(new java.awt.Color(255, 255, 255));
        btn_petugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Officer.png"))); // NOI18N
        btn_petugas.setText("Petugas");
        btn_petugas.setActionCommand("");
        btn_petugas.setAlignmentY(0.0F);
        btn_petugas.setBorder(null);
        btn_petugas.setBorderPainted(false);
        btn_petugas.setContentAreaFilled(false);
        btn_petugas.setDefaultCapable(false);
        btn_petugas.setFocusCycleRoot(true);
        btn_petugas.setFocusTraversalPolicyProvider(true);
        btn_petugas.setHideActionText(true);
        btn_petugas.setInheritsPopupMenu(true);
        btn_petugas.setOpaque(true);
        btn_petugas.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_petugas.setRequestFocusEnabled(false);
        btn_petugas.setRolloverEnabled(false);
        btn_petugas.setVerifyInputWhenFocusTarget(false);
        btn_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_petugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_petugasMouseExited(evt);
            }
        });
        pnlMenu.add(btn_petugas);

        btn_pembayaran.setBackground(new java.awt.Color(255, 153, 255));
        btn_pembayaran.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pembayaran.setForeground(new java.awt.Color(255, 255, 255));
        btn_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Card.png"))); // NOI18N
        btn_pembayaran.setText("Pembayaran");
        btn_pembayaran.setActionCommand("");
        btn_pembayaran.setAlignmentY(0.0F);
        btn_pembayaran.setBorder(null);
        btn_pembayaran.setBorderPainted(false);
        btn_pembayaran.setContentAreaFilled(false);
        btn_pembayaran.setDefaultCapable(false);
        btn_pembayaran.setFocusCycleRoot(true);
        btn_pembayaran.setFocusTraversalPolicyProvider(true);
        btn_pembayaran.setHideActionText(true);
        btn_pembayaran.setInheritsPopupMenu(true);
        btn_pembayaran.setOpaque(true);
        btn_pembayaran.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_pembayaran.setRequestFocusEnabled(false);
        btn_pembayaran.setRolloverEnabled(false);
        btn_pembayaran.setVerifyInputWhenFocusTarget(false);
        btn_pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pembayaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pembayaranMouseExited(evt);
            }
        });
        pnlMenu.add(btn_pembayaran);

        btn_laporan.setBackground(new java.awt.Color(255, 153, 255));
        btn_laporan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Graph Report.png"))); // NOI18N
        btn_laporan.setText("Laporan");
        btn_laporan.setActionCommand("");
        btn_laporan.setAlignmentY(0.0F);
        btn_laporan.setBorder(null);
        btn_laporan.setBorderPainted(false);
        btn_laporan.setContentAreaFilled(false);
        btn_laporan.setDefaultCapable(false);
        btn_laporan.setFocusCycleRoot(true);
        btn_laporan.setFocusTraversalPolicyProvider(true);
        btn_laporan.setHideActionText(true);
        btn_laporan.setInheritsPopupMenu(true);
        btn_laporan.setOpaque(true);
        btn_laporan.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_laporan.setRequestFocusEnabled(false);
        btn_laporan.setRolloverEnabled(false);
        btn_laporan.setVerifyInputWhenFocusTarget(false);
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_laporanMouseExited(evt);
            }
        });
        pnlMenu.add(btn_laporan);

        btn_logout.setBackground(new java.awt.Color(255, 153, 255));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setActionCommand("");
        btn_logout.setAlignmentY(0.0F);
        btn_logout.setBorder(null);
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setDefaultCapable(false);
        btn_logout.setFocusCycleRoot(true);
        btn_logout.setFocusTraversalPolicyProvider(true);
        btn_logout.setHideActionText(true);
        btn_logout.setInheritsPopupMenu(true);
        btn_logout.setOpaque(true);
        btn_logout.setPreferredSize(new java.awt.Dimension(180, 40));
        btn_logout.setRequestFocusEnabled(false);
        btn_logout.setRolloverEnabled(false);
        btn_logout.setVerifyInputWhenFocusTarget(false);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_logout);

        getContentPane().add(pnlMenu, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(242, 185, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(833, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lbl_user.setBackground(new java.awt.Color(242, 209, 227));
        lbl_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AdminitratorBlck.png"))); // NOI18N
        lbl_user.setText("Selamat Datang di Administrator");
        jPanel1.add(lbl_user, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane3.setViewportView(jPanel4);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1029, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_administratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_administratorMouseEntered
        // TODO add your handling code here:
        btn_administrator.setBackground(backNavHover);
        btn_administrator.setForeground(foreNavHover);
        btn_administrator.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\AdminitratorBlck.png"));
    }//GEN-LAST:event_btn_administratorMouseEntered

    private void btn_administratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_administratorMouseExited
        // TODO add your handling code here:
        btn_administrator.setBackground(backNavNormal);
        btn_administrator.setForeground(foreNavNormal);
        btn_administrator.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Adminitrator.png"));
    }//GEN-LAST:event_btn_administratorMouseExited

    private void btn_sppMouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sppMouseEntered1
        // TODO add your handling code here:
        btn_spp.setBackground(backNavHover);
        btn_spp.setForeground(foreNavHover);
        btn_spp.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\paymentblck.png"));

    }//GEN-LAST:event_btn_sppMouseEntered1

    private void btn_sppMouseExited1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sppMouseExited1
        // TODO add your handling code here:
        btn_spp.setBackground(backNavNormal);
        btn_spp.setForeground(foreNavNormal);
        btn_spp.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\payment.png"));

    }//GEN-LAST:event_btn_sppMouseExited1

    private void btn_kelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelasMouseEntered
        // TODO add your handling code here:
        btn_kelas.setBackground(backNavHover);
        btn_kelas.setForeground(foreNavHover);
        btn_kelas.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Classblck.png"));

    }//GEN-LAST:event_btn_kelasMouseEntered

    private void btn_kelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelasMouseExited
        // TODO add your handling code here:
        btn_kelas.setBackground(backNavNormal);
        btn_kelas.setForeground(foreNavNormal);
        btn_kelas.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Class.png"));
    }//GEN-LAST:event_btn_kelasMouseExited

    private void btn_siswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siswaMouseEntered
        // TODO add your handling code here:
        btn_siswa.setBackground(backNavHover);
        btn_siswa.setForeground(foreNavHover);
        btn_siswa.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Studentblck.png"));

    }//GEN-LAST:event_btn_siswaMouseEntered

    private void btn_siswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siswaMouseExited
        // TODO add your handling code here:
        btn_siswa.setBackground(backNavNormal);
        btn_siswa.setForeground(foreNavNormal);
        btn_siswa.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Student.png"));

    }//GEN-LAST:event_btn_siswaMouseExited

    private void btn_petugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseEntered
        // TODO add your handling code here:
        btn_petugas.setBackground(backNavHover);
        btn_petugas.setForeground(foreNavHover);
        btn_petugas.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Officerblck.png"));
    }//GEN-LAST:event_btn_petugasMouseEntered

    private void btn_petugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_petugasMouseExited
        // TODO add your handling code here:
        btn_petugas.setBackground(backNavNormal);
        btn_petugas.setForeground(foreNavNormal);
        btn_petugas.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Officer.png"));
    }//GEN-LAST:event_btn_petugasMouseExited

    private void btn_pembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembayaranMouseEntered
        // TODO add your handling code here:
        btn_pembayaran.setBackground(backNavHover);
        btn_pembayaran.setForeground(foreNavHover);
        btn_pembayaran.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Cardblck.png"));
    }//GEN-LAST:event_btn_pembayaranMouseEntered

    private void btn_pembayaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembayaranMouseExited
        // TODO add your handling code here:
        btn_pembayaran.setBackground(backNavNormal);
        btn_pembayaran.setForeground(foreNavNormal);
        btn_pembayaran.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Card.png"));
    }//GEN-LAST:event_btn_pembayaranMouseExited

    private void btn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseEntered
        // TODO add your handling code here:
        btn_laporan.setBackground(backNavHover);
        btn_laporan.setForeground(foreNavHover);
        btn_laporan.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Graphblck.png"));
    }//GEN-LAST:event_btn_laporanMouseEntered

    private void btn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseExited
        // TODO add your handling code here:
        btn_laporan.setBackground(backNavNormal);
        btn_laporan.setForeground(foreNavNormal);
        btn_laporan.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Graph Report.png"));
    }//GEN-LAST:event_btn_laporanMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
        btn_logout.setBackground(backNavHover);
        btn_logout.setForeground(foreNavHover);
        btn_logout.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Logoutblk.png"));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
        btn_logout.setBackground(backNavNormal);
        btn_logout.setForeground(foreNavNormal);
        btn_logout.setIcon(new ImageIcon("D:\\PPG Prajabatan\\Pembelajaran\\PembayaranSPPNetbeansJava\\PembayaranSPP\\src\\image\\Logout.png"));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new login_admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_administrator;
    private javax.swing.JButton btn_kelas;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pembayaran;
    private javax.swing.JButton btn_petugas;
    private javax.swing.JButton btn_siswa;
    private javax.swing.JButton btn_spp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_fotouser;
    private javax.swing.JLabel lbl_namauser;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
